base_model_path: "/home/weight/DeepSeek-V3.2"
is_mm: false
is_deepseek_v32: true

# -----------------------------------------------
# 工作区 (运行时文件)
# -----------------------------------------------
workspace_base_dir: "workspace"
workspace_current_run_dir: "current_run"
workspace_best_weights_dir: "best_weights"
workspace_quant_weights_dir: "quantized_weights"

# -----------------------------------------------
# 核心调优策略（仅无 AQT 时使用固定回退层）
# -----------------------------------------------
strategy_initial_fallback_layers:
  - 'lm_head'

# -----------------------------------------------
# 评估配置
# -----------------------------------------------
evaluation_tolerance_ratio: 1.0
disable_qwen_thinking: false

evaluation_datasets:
  aime2024:
    config_name: "aime2024_gen_0_shot_chat_prompt"
    mode: "all"
    target_accuracy: 90.0
    tolerance_ratio: 6.67
    metric_keys:
      - "aime2024_accuracy"
  aime2025:
    config_name: "aime2025_gen"
    mode: "all"
    target_accuracy: 83.33
    tolerance_ratio: 3.34
    metric_keys:
      - "aime2025_accuracy"
  gpqa:
    config_name: "gpqa_gen_0_shot_cot_chat_prompt"
    mode: "all"
    target_accuracy: 81.0

aisbench_timeout: 7200
aisbench_request_rate: 0
aisbench_retry: 2
aisbench_batch_size: 60
aisbench_max_out_len: 32768
aisbench_pred_postprocessor: "extract_non_reasoning_content"
aisbench_generation_kwargs:
  temperature: 0.5
  top_k: 10
  top_p: 0.95
  seed: null
  repetition_penalty: 1.03
  chat_template_kwargs:
    thinking: True
aisbench_log_dir: "workspace/aisbench_logs"
aisbench_default_metric_keys:
  - "final_accuracy"
  - "accuracy"
  - "score"
aisbench_use_chat_template: true
aisbench_cleanup_model_config: true
aisbench_extra_args: null

# -----------------------------------------------
# VLLM-Ascend Server
# -----------------------------------------------
vllm_port: 1234
vllm_env_vars:
  HCCL_OP_RETRY_ENABLE: "L0:0, L1:0, L2:0"
  # TODO: 根据实际情况修改 ip 和 网卡名(ip addr show 查看所有网卡信息)
  HCCL_IF_IP: 90.90.97.14
  GLOO_SOCKET_IFNAME: "enp194s0f0"
  TP_SOCKET_IFNAME: "enp194s0f0"
  HCCL_SOCKET_IFNAME: "enp194s0f0"
  HCCL_BUFFSIZE: 1024
  # TODO: 根据实际情况修改用的卡号
  ASCEND_RT_VISIBLE_DEVICES: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
  HCCL_OP_EXPANSION_MODE: "AIV"
  PYTORCH_NPU_ALLOC_CONF: "expandable_segments:True"
  OMP_PROC_BIND: false
  ATB_LLM_HCCL_ENABLE: 1
  ATB_LLM_COMM_BACKEND: "lccl"
  OMP_NUM_THREADS: 10
  VLLM_RPC_TIMEOUT: 300
  VLLM_ENGINE_READY_TIMEOUT_S: 1800
vllm_args:
  trust-remote-code: true
  tensor-parallel-size: 8
  data-parallel-size: 2
  enable-expert-parallel: true
  async-scheduling: true
  enable-prefix-caching: false
  max-num-seqs: 32
  max-model-len: 40960
  max-num-batched-tokens: 8192
  gpu-memory-utilization: 0.85
  additional-config:
    ascend_scheduler_config:
      enabled: false
    enable_cpu_binding: true
    multistream_overlap_shared_expert: true
  speculative-config:
    num_speculative_tokens: 1
    method: "deepseek_mtp"
  compilation-config:
    cudagraph_mode: "FULL_DECODE_ONLY"
    cudagraph_capture_sizes: [1,2,4,8,16,32]

# -----------------------------------------------
# Automatic Quantization Tool (AQT)
# -----------------------------------------------
aqt_enabled: true
aqt_results_dir: "workspace/aqt_results"
aqt_omp_num_threads: 32
# TODO: 根据实际情况修改用的卡号
aqt_ascend_visible_devices: "0"
# 校准集
aqt_quant_data_path: "/home/f50049642/calib_data.txt"     # 必填：校准集路径
aqt_quant_samples_num: 8
aqt_quant_context_length: 1024
# 敏感度指标
aqt_sensitivity_metrics: ["mse", "cosine", "kl_div"]
# 回退预算
aqt_initial_budget_mb: 0
aqt_budget_step_mb: 1000
aqt_budget_step_down_mb: 1000
aqt_min_budget_mb: 0
aqt_max_budget_mb: 25000

# -----------------------------------------------
# 量化器配置
# -----------------------------------------------
# quantization_tool: "llmcompressor"
# enable_smooth_quant: false
# smooth_strength: 0.8
# quantization_visible_devices: "1"
# quantization_device: "npu"
# quantization_model_type: "Qwen3-30B"
# quantization_calib_data_path: ""
# num_calibration_samples: 512
# max_sequence_length: 2048
# quantization_modifier: "PTQ"

quantization_tool: "msmodelslim"
# TODO: 根据实际情况修改用的卡号
quantization_visible_devices: "1"
quantization_model_type: "DeepSeek-V3.2"
quantization_device: "npu"
quantization_trust_remote_code: true

# Modelslim YAML 配置模板
quantization_template_config:
  w_bit: 4  # 权重量化位数
  a_bit: 8  # 激活量化位数

  v1:
    metadata:
      config_id: deepseekv32-w4a8-v1
      score: 90
      label:
        is_sparse: false
        kv_cache: false

    qconfigs:
      default_w8a8_dynamic:
        act:
          scope: "per_token"      # 激活值量化范围: per_token 或 per_tensor
          dtype: "int8"           # 数据类型: int8
          symmetric: true         # 是否对称量化
          method: "minmax"        # 量化方法: minmax
        weight:
          scope: "per_channel"    # 权重量化范围: per_channel 或 per_group
          dtype: "int8"           # 数据类型: int8
          symmetric: true         # 是否对称量化
          method: "minmax"        # 量化方法: minmax, ssz

      default_w4a8_dynamic_perchannel:
        act:
          scope: "per_token"
          dtype: "int8"
          symmetric: true
          method: "minmax"
        weight:
          scope: "per_channel"
          dtype: "int4"
          symmetric: true
          method: "ssz"

    process:
      # TODO: 开启后量化耗时过久，选择性开启
      # - type: "quarot"
      # - type: "flex_awq_ssz"
      #   qconfig:
      #     act:
      #       scope: "per_token"
      #       dtype: "int8"
      #       symmetric: True
      #       method: "minmax"
      #     weight:
      #       scope: "per_channel"
      #       dtype: "int4"
      #       symmetric: True
      #       method: "ssz"
      #       ext:
      #         step: 10
      #   enable_subgraph_type:
      #     - 'up-down'
      #   include:
      #     - "*"
      #   exclude:
      #     - "model.layers.0.*"
      #     - "model.layers.1.*"
      #     - "model.layers.2.*"
      #     - "*mlp.shared_experts.*"
      # - type: "flex_smooth_quant"
      #   enable_subgraph_type:
      #     - 'norm-linear'
      #     - 'ov'
      #     - 'up-down'
      #   include:
      #     - "*self_attn*"
      #     - "model.layers.0.mlp.*"
      #     - "model.layers.1.mlp.*"
      #     - "model.layers.2.mlp.*"
      #     - "*mlp.shared_experts.*"
      #     - "*input_layernorm*"
      #   exclude:
      #     - "*post_attention_layernorm*"
      - type: "group"
        configs:
          - type: "linear_quant"
            qconfig_ref: "default_w4a8_dynamic_perchannel"
          - type: "linear_quant"
            qconfig_ref: "default_w8a8_dynamic"

    save:
      - type: "ascendv1_saver"
        part_file_size: 4
