base_model_path: "/home/zc_test/Qwen3.5-27B"
is_mm: true
is_deepseek_v32: false

# -----------------------------------------------
# 工作区 (运行时文件)
# -----------------------------------------------
workspace_base_dir: "workspace-Qwen3.5-27B"
workspace_current_run_dir: "current_run"
workspace_best_weights_dir: "best_weights"
workspace_quant_weights_dir: "quantized_weights"

# -----------------------------------------------
# 核心调优策略（仅无 AQT 时使用固定回退层）
# -----------------------------------------------
strategy_initial_fallback_layers:
  - 'lm_head'

# -----------------------------------------------
# 评估配置
# -----------------------------------------------
evaluation_tolerance_ratio: 1.0
disable_qwen_thinking: false

evaluation_datasets:
  aime2024:
    config_name: "aime2024_gen_0_shot_chat_prompt"
    mode: "all"
    target_accuracy: 86.67
    tolerance_ratio: 6.67
    metric_keys:
      - "aime2024_accuracy"
  aime2025:
    config_name: "aime2025_gen"
    mode: "all"
    target_accuracy: 80.0
    tolerance_ratio: 3.34
    metric_keys:
      - "aime2025_accuracy"
  gpqa:
    config_name: "gpqa_gen_0_shot_cot_chat_prompt"
    mode: "all"
    target_accuracy: 85.35

aisbench_timeout: 7200
aisbench_request_rate: 0
aisbench_retry: 2
aisbench_batch_size: 64
aisbench_max_out_len: 32768
aisbench_pred_postprocessor: "extract_non_reasoning_content"
aisbench_generation_kwargs:
  temperature: 0.5
  top_k: 10
  top_p: 0.95
  seed: null
  repetition_penalty: 1.03
aisbench_log_dir: "workspace-Qwen3.5-27B/aisbench_logs"
aisbench_default_metric_keys:
  - "final_accuracy"
  - "accuracy"
  - "score"
aisbench_use_chat_template: true
aisbench_cleanup_model_config: true
aisbench_extra_args: null

# -----------------------------------------------
# VLLM-Ascend Server
# -----------------------------------------------
vllm_port: 1234
vllm_env_vars:
  HCCL_OP_RETRY_ENABLE: "L0:0, L1:0, L2:0"
  HCCL_BUFFSIZE: 1024
  # TODO: 根据实际情况修改用的卡号
  ASCEND_RT_VISIBLE_DEVICES: "0,1,2,3"
  OMP_PROC_BIND: false
  ATB_LLM_HCCL_ENABLE: 1
  ATB_LLM_COMM_BACKEND: "lccl"
  HCCL_OP_EXPANSION_MODE: "AIV"
  PYTORCH_NPU_ALLOC_CONF: "expandable_segments:True"
  TASK_QUEUE_ENABLE: 1
  CPU_AFFINITY_CONF: 1
  OMP_NUM_THREADS: 10
  TORCHDYNAMO_ALLOW_INTERNAL_API: 1
  VLLM_INDUCTOR_NO_FALLBACK: 0
  MIES_USE_MB_SWAPPER: 1
vllm_args:
  trust-remote-code: true
  tensor-parallel-size: 4
  data-parallel-size: 1
  async-scheduling: true
  enable-prefix-caching: false
  max-num-seqs: 64
  allowed-local-media-path: "/"
  max-model-len: 40960
  max-num-batched-tokens: 16384
  gpu-memory-utilization: 0.55
  additional-config:
    ascend_scheduler_config:
      enabled: false
    enable_cpu_binding: true
  compilation-config:
    cudagraph_mode: "FULL_DECODE_ONLY"
    cudagraph_capture_sizes: [1,2,4,8,16,32,64]

# -----------------------------------------------
# Automatic Quantization Tool (AQT)
# -----------------------------------------------
aqt_enabled: true
aqt_results_dir: "workspace-Qwen3.5-27B/aqt_results"
aqt_omp_num_threads: 32
# TODO: 根据实际情况修改用的卡号
aqt_ascend_visible_devices: "0"
# 校准集
aqt_quant_data_path: "/home/kongjunyu/calib_data.txt"     # 必填：校准集路径
aqt_quant_samples_num: 32
aqt_quant_context_length: 2048
# 敏感度指标
aqt_sensitivity_metrics: ["mse", "cosine", "relative_l2", "kl_div"]
# 回退预算
aqt_initial_budget_mb: 0
aqt_budget_step_mb: 200
aqt_budget_step_down_mb: 100
aqt_min_budget_mb: 0
aqt_max_budget_mb: 2500

# -----------------------------------------------
# 量化器配置
# -----------------------------------------------
# quantization_tool: "llmcompressor"
# enable_smooth_quant: false
# smooth_strength: 0.8
# quantization_visible_devices: "1"
# quantization_device: "npu"
# quantization_model_type: "Qwen3-30B"
# quantization_calib_data_path: ""
# num_calibration_samples: 512
# max_sequence_length: 2048
# quantization_modifier: "PTQ"
quantization_tool: "msmodelslim"
# TODO: 根据实际情况修改用的卡号
quantization_visible_devices: "1"
quantization_model_type: "Qwen3.5-27B"
quantization_device: "npu"
quantization_trust_remote_code: true

# Modelslim YAML 配置模板
quantization_template_config:
  w_bit: 4  # 权重量化位数
  a_bit: 8  # 激活量化位数

  v1:
    metadata:
      config_id: qwen3.5-dense-w8a8-v1
      score: 90
      label:
        is_sparse: false
        kv_cache: false

    qconfigs:
      default_w8a8_dynamic:
        act:
          scope: "per_token"      # 激活值量化范围: per_token 或 per_tensor
          dtype: "int8"           # 数据类型: int8
          symmetric: true         # 是否对称量化
          method: "minmax"        # 量化方法: minmax
        weight:
          scope: "per_channel"    # 权重量化范围: per_channel 或 per_group
          dtype: "int8"           # 数据类型: int8
          symmetric: true         # 是否对称量化
          method: "minmax"        # 量化方法: minmax, ssz

    process:
      - type: "group"
        configs:
          - type: "linear_quant"
            qconfig_ref: "default_w8a8_dynamic"

    save:
      - type: "ascendv1_saver"
        part_file_size: 4
